import { ArticleType } from '../types/entities/articleType';
import { CommentType } from '../types/entities/commentType';
import { MyProfileType, ProfileType } from '../types/entities/profileType';
import { ReactionType } from '../types/entities/reactionType';

export const articles: ArticleType[] = [
  {
    id: 1,
    title: 'Test Article',
    description:
      'Test description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this article',
    banner:
      'https://habrastorage.org/r/w1560/getpro/habr/upload_files/a05/7e4/65c/a057e465c18222626573b33218de2cde.png',
    content: [
      {
        type: 'title',
        text: 'Заголовок 1',
      },
      {
        type: 'text',
        text: 'Параграф №1. Это текст.',
      },
      {
        type: 'img',
        src: 'https://habrastorage.org/r/w1560/getpro/habr/upload_files/e7e/70c/b44/e7e70cb44ac6efa98a3458812989b333.png',
        text: 'Описание картинки',
      },
      {
        type: 'title',
        text: 'Заголовок 2',
      },
      {
        type: 'quote',
        text: 'Параграф №2. Это текст.',
      },
      {
        type: 'ol',
        list: ['Первый случай', 'Второй случай', 'Третий случай'],
      },
      {
        type: 'ul',
        list: ['Первый случай', 'Второй случай', 'Третий случай'],
      },
    ],
    status: 'public',
    createdAt: Date.now(),
    updatedAt: null,
    authorLogin: 'shp0ks',
    authorUsername: 'Shpaks',
    authorAvatar: null,
    reactions: [],
    comments: [
      {
        id: 1,
        content: 'Test comment',
        createdAt: Date.now(),
        updatedAt: null,
        authorLogin: 'skebob',
        authorUsername: 'Матвей',
        authorAvatar: null,
        parent: null,
        relatedId: 1,
        relatedType: 'article',
        reactions: [],
      },
      {
        id: 2,
        content: 'Test comment 2',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        authorLogin: 'skebob2',
        authorUsername: 'Матвей 2',
        authorAvatar: null,
        parent: {
          id: 1,
          authorUsername: 'Матвей',
          relatedType: 'article',
          text: 'Test comment',
        },
        relatedId: 1,
        relatedType: 'article',
        reactions: [],
      },
    ],
  },
  {
    id: 2,
    title: 'Test Article',
    description: 'Test description for this article',
    banner: null,
    content: [],
    status: 'public',
    createdAt: Date.now(),
    updatedAt: null,
    authorLogin: 'shp0ks',
    authorUsername: 'Shpaks',
    authorAvatar: null,
    reactions: [],
    comments: [],
  },
];

export const comments: CommentType[] = [
  {
    id: 1,
    content: 'Test comment',
    createdAt: Date.now(),
    updatedAt: null,
    authorLogin: 'skebob',
    authorUsername: 'Матвей',
    authorAvatar: null,
    parent: null,
    relatedId: 1,
    relatedType: 'article',
    reactions: [],
  },
  {
    id: 2,
    content: 'Test comment 2',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    authorLogin: 'skebob2',
    authorUsername: 'Матвей 2',
    authorAvatar: null,
    parent: {
      id: 1,
      authorUsername: 'Матвей',
      relatedType: 'article',
      text: 'Test comment',
    },
    relatedId: 1,
    relatedType: 'article',
    reactions: [],
  },
];

export const reactions: ReactionType[] = [
  {
    id: 1,
    type: 'dislike',
    authorLogin: 'shp0ks',
    relatedId: 1,
    relatedType: 'article',
  },
  {
    id: 2,
    type: 'like',
    authorLogin: 'shp0ks',
    relatedId: 1,
    relatedType: 'post',
  },
  {
    id: 3,
    type: 'like',
    authorLogin: 'test',
    relatedId: 2,
    relatedType: 'article',
  },
];

export const testUser: ProfileType = {
  login: 'Ifnuh666',
  username: 'Максим',
  avatar: null,
  articles: [
    {
      id: 1,
      title: 'Test Article',
      description:
        'Test description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this article',
      banner: null,
      content: [],
      status: 'public',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'shp0ks',
      authorUsername: 'Shpaks',
      authorAvatar: null,
      reactions: [],
      comments: [
        {
          id: 1,
          content: 'Test comment',
          createdAt: Date.now(),
          updatedAt: null,
          authorLogin: 'skebob',
          authorUsername: 'Матвей',
          authorAvatar: null,
          parent: null,
          relatedId: 1,
          relatedType: 'article',
          reactions: [],
        },
        {
          id: 2,
          content: 'Test comment 2',
          createdAt: Date.now(),
          updatedAt: Date.now(),
          authorLogin: 'skebob2',
          authorUsername: 'Матвей 2',
          authorAvatar: null,
          parent: {
            id: 1,
            authorUsername: 'Матвей',
            relatedType: 'article',
            text: 'Test comment',
          },
          relatedId: 1,
          relatedType: 'article',
          reactions: [],
        },
      ],
    },
    {
      id: 2,
      title: 'Test Article',
      description: 'Test description for this article',
      banner: null,
      content: [],
      status: 'public',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'shp0ks',
      authorUsername: 'Shpaks',
      authorAvatar: null,
      reactions: [],
      comments: [],
    },
  ],
  comments: [
    {
      id: 1,
      content: 'Test comment',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'skebob',
      authorUsername: 'Матвей',
      authorAvatar: null,
      parent: null,
      relatedId: 1,
      relatedType: 'article',
      reactions: [],
    },
    {
      id: 2,
      content: 'Test comment 2',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      authorLogin: 'skebob2',
      authorUsername: 'Матвей 2',
      authorAvatar: null,
      parent: {
        id: 1,
        authorUsername: 'Матвей',
        relatedType: 'article',
        text: 'Test comment',
      },
      relatedId: 1,
      relatedType: 'article',
      reactions: [],
    },
  ],
  reactions: [
    {
      id: 1,
      type: 'dislike',
      authorLogin: 'shp0ks',
      relatedId: 1,
      relatedType: 'article',
    },
    {
      id: 2,
      type: 'like',
      authorLogin: 'shp0ks',
      relatedId: 1,
      relatedType: 'post',
    },
    {
      id: 3,
      type: 'like',
      authorLogin: 'test',
      relatedId: 2,
      relatedType: 'article',
    },
  ],
};

export const testMyUser: MyProfileType = {
  login: 'shp0ks',
  username: 'Shpaks',
  avatar: null,
  articles: [
    {
      id: 1,
      title: 'Test Article',
      description:
        'Test description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this articleTest description for this article',
      banner: null,
      content: [],
      status: 'public',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'shp0ks',
      authorUsername: 'Shpaks',
      authorAvatar: null,
      reactions: [],
      comments: [
        {
          id: 1,
          content: 'Test comment',
          createdAt: Date.now(),
          updatedAt: null,
          authorLogin: 'skebob',
          authorUsername: 'Матвей',
          authorAvatar: null,
          parent: null,
          relatedId: 1,
          relatedType: 'article',
          reactions: [],
        },
        {
          id: 2,
          content: 'Test comment 2',
          createdAt: Date.now(),
          updatedAt: Date.now(),
          authorLogin: 'skebob2',
          authorUsername: 'Матвей 2',
          authorAvatar: null,
          parent: {
            id: 1,
            authorUsername: 'Матвей',
            relatedType: 'article',
            text: 'Test comment',
          },
          relatedId: 1,
          relatedType: 'article',
          reactions: [],
        },
      ],
    },
    {
      id: 2,
      title: 'Test Article',
      description: 'Test description for this article',
      banner: null,
      content: [],
      status: 'public',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'shp0ks',
      authorUsername: 'Shpaks',
      authorAvatar: null,
      reactions: [],
      comments: [],
    },
  ],
  comments: [
    {
      id: 1,
      content: 'Test comment',
      createdAt: Date.now(),
      updatedAt: null,
      authorLogin: 'skebob',
      authorUsername: 'Матвей',
      authorAvatar: null,
      parent: null,
      relatedId: 1,
      relatedType: 'article',
      reactions: [],
    },
    {
      id: 2,
      content: 'Test comment 2',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      authorLogin: 'skebob2',
      authorUsername: 'Матвей 2',
      authorAvatar: null,
      parent: {
        id: 1,
        authorUsername: 'Матвей',
        relatedType: 'article',
        text: 'Test comment',
      },
      relatedId: 1,
      relatedType: 'article',
      reactions: [],
    },
  ],
  reactions: [
    {
      id: 1,
      type: 'dislike',
      authorLogin: 'shp0ks',
      relatedId: 1,
      relatedType: 'article',
    },
    {
      id: 2,
      type: 'like',
      authorLogin: 'shp0ks',
      relatedId: 1,
      relatedType: 'post',
    },
    {
      id: 3,
      type: 'like',
      authorLogin: 'test',
      relatedId: 2,
      relatedType: 'article',
    },
  ],
};
